### Consultar estudiantes
GET http://127.0.0.1:8000/api/app/estudiantes

### Crear un nuevo estudiante
POST http://127.0.0.1:8000/api/app/estudiante
Content-Type: "application/json"

{
    "codigo"; "000",
    "nombre": "Andres",
    "email": "andres@test.com"
}

